version: '3'

services:
  postgres:
    image: postgres:16-alpine3.18
    env_file:
      - postgresql.env
    ports:
      - "5432:5432"
    networks:
      - net
    profiles:
      - postgresql

networks:
  net:
    driver: bridge
